name: Build and Release domgrep

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release .deb Package
    runs-on: ubuntu-latest

    env:
      DEB_ARCH: amd64  # Set architecture explicitly
      PACKAGE_NAME: domgrep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev debhelper fakeroot gzip

      - name: Bump version (patch by default)
        run: |
          chmod +x scripts/bump_version.sh
          ./scripts/bump_version.sh patch

      - name: Read new version
        id: version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      # -------------------- Build Step --------------------
      - name: Prepare package structure
        run: |
          mkdir -p pkg/DEBIAN
          mkdir -p pkg/usr/lib/${{ env.PACKAGE_NAME }}
          mkdir -p pkg/usr/bin
          mkdir -p pkg/usr/share/man/man1
          mkdir -p pkg/usr/share/doc/${{ env.PACKAGE_NAME }}

          # Control and postinst
          cp debian/control pkg/DEBIAN/control
          cp debian/postinst pkg/DEBIAN/postinst
          chmod 755 pkg/DEBIAN/postinst

          # Shell scripts
          cp src/*.sh pkg/usr/lib/${{ env.PACKAGE_NAME }}/

          # Man page
          cp man/${{ env.PACKAGE_NAME }}.1 pkg/usr/share/man/man1/
          gzip -9 -f pkg/usr/share/man/man1/${{ env.PACKAGE_NAME }}.1

          # Documentation
          cp README.md pkg/usr/share/doc/${{ env.PACKAGE_NAME }}/
          cp debian/changelog pkg/usr/share/doc/${{ env.PACKAGE_NAME }}/
          cp debian/copyright pkg/usr/share/doc/${{ env.PACKAGE_NAME }}/
          gzip -9 -f pkg/usr/share/doc/${{ env.PACKAGE_NAME }}/changelog

          # Entry point
          echo '#!/bin/sh' > pkg/usr/bin/${{ env.PACKAGE_NAME }}
          echo "exec /usr/lib/${{ env.PACKAGE_NAME }}/${{ env.PACKAGE_NAME }}.sh \"\$@\"" >> pkg/usr/bin/${{ env.PACKAGE_NAME }}
          chmod +x pkg/usr/bin/${{ env.PACKAGE_NAME }}

          # Fix ownership
          sudo chown -R root:root pkg/

      - name: Build .deb package
        run: |
          export DEB_VERSION=${{ steps.version.outputs.version }}
          export DEB_FILE="${{ env.PACKAGE_NAME }}_${DEB_VERSION}_${{ env.DEB_ARCH }}.deb"
          dpkg-deb --build pkg "$DEB_FILE"
          echo "deb_file=$DEB_FILE" >> $GITHUB_ENV

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: domgrep-deb
          path: ${{ env.deb_file }}

      # -------------------- Release Step --------------------
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.version.outputs.version }}"
          release_name: "domgrep v${{ steps.version.outputs.version }}"
          body: "Automated release for domgrep version v${{ steps.version.outputs.version }}"
          files: "${{ env.deb_file }}"
          draft: false
          prerelease: false
          overwrite: true
