name: Build and Release .deb package

on:
  push:
    tags:
      - 'v*.*.*'   # Trigger only on version tags, e.g., v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Debian build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y devscripts debhelper build-essential lintian

    - name: Build .deb package
      run: |
        dpkg-buildpackage -us -uc

    - name: List generated packages
      run: ls -l ../*.deb

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: ../domgrep_*.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
